
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETE_CERRADO = 6;
  public static final int STRING_PARAMETRO = 90;
  public static final int DECIMAL_POSITIVO = 91;
  public static final int MENOR_IGUAL = 60;
  public static final int MENOR_QUE = 2;
  public static final int C_P = 27;
  public static final int TYPE = 37;
  public static final int ROWS = 39;
  public static final int TIPOS_DATOS = 62;
  public static final int DIAGONAL = 4;
  public static final int ASC = 67;
  public static final int CORCHETE_ABIERTO = 5;
  public static final int NAME = 30;
  public static final int ALING_PARAMETRO = 51;
  public static final int INIT = 79;
  public static final int C_GCIC = 11;
  public static final int ALT = 45;
  public static final int DIFERENTE = 59;
  public static final int TEXT_ALIGN = 36;
  public static final int LETIMPAR_NUM = 70;
  public static final int MAYOR_QUE = 3;
  public static final int C_LINK = 14;
  public static final int IGUAL_IGUAL = 58;
  public static final int C_OPTION = 21;
  public static final int NOT = 104;
  public static final int BACKGROUND = 31;
  public static final int THENWHILE = 87;
  public static final int C_SPAM = 17;
  public static final int THEN = 82;
  public static final int DOS_PUNTOS = 99;
  public static final int ID_PARAMETRO_INSERT = 57;
  public static final int C_BODY = 16;
  public static final int WIDTH = 43;
  public static final int REVERSE = 71;
  public static final int C_TEXTAREA = 19;
  public static final int PUNTO_COMA = 98;
  public static final int CLASS = 41;
  public static final int ALERT_INFO = 74;
  public static final int C_DIV = 22;
  public static final int C_HEAD = 12;
  public static final int REDIRECT = 76;
  public static final int COMA = 9;
  public static final int NUM_ALEATORIO = 73;
  public static final int HUNTIL = 85;
  public static final int ENTERO = 40;
  public static final int C_SCRIPTING = 28;
  public static final int C_INPUT = 18;
  public static final int GET_ELEMENT_BY_ID = 78;
  public static final int IGUAL = 10;
  public static final int COLOR_PARAMETRO = 33;
  public static final int WHILE = 86;
  public static final int COLS = 38;
  public static final int INTEGER_POSITIVO = 89;
  public static final int BOOLEAN = 93;
  public static final int LLAVE_CERRADA = 101;
  public static final int DECIMAL_NEGATIVO = 92;
  public static final int LINK_PARAMETRO = 15;
  public static final int ELSE = 83;
  public static final int TEXTO_ETIQUETA = 54;
  public static final int C_BR = 24;
  public static final int EOF = 0;
  public static final int SUMA = 96;
  public static final int C_TITLE = 13;
  public static final int LLAVE_ABIERTA = 100;
  public static final int CARACTER = 94;
  public static final int REPEAT = 84;
  public static final int C_IMG = 23;
  public static final int SRC = 42;
  public static final int NOMBRE_FUNCION = 65;
  public static final int HREF = 47;
  public static final int EXIT = 75;
  public static final int error = 1;
  public static final int OPERADOR_Y = 102;
  public static final int RESTA = 97;
  public static final int ID_PARAMETRO = 55;
  public static final int IF = 81;
  public static final int PARENTESIS_CERRADO = 8;
  public static final int DESC = 68;
  public static final int ID = 29;
  public static final int COLOR = 32;
  public static final int ON_LOAD = 66;
  public static final int C_SELECT = 20;
  public static final int OPERADOR_O = 103;
  public static final int END = 80;
  public static final int SIZE_PARAMETRO = 49;
  public static final int SIZE_PARAMETRO_IMAGEN = 48;
  public static final int C_H1 = 26;
  public static final int ID_VARIABLE = 63;
  public static final int MULTIPLICACION = 95;
  public static final int HEIGHT = 44;
  public static final int TYPE_PARAMETRO = 52;
  public static final int ID_PARAMETRO_ELEMENT = 56;
  public static final int GLOBAL = 64;
  public static final int CARACTER_ALEATORIO = 72;
  public static final int FONT_FAMILY = 35;
  public static final int FONT_SIZE = 34;
  public static final int INTEGER_NEGATIVO = 88;
  public static final int INSERT = 77;
  public static final int NOMBRE_FUNCION_PARAMETRO = 53;
  public static final int ONCLICK = 46;
  public static final int PARENTESIS_ABIERTO = 7;
  public static final int C_BUTTON = 25;
  public static final int LETPAR_NUM = 69;
  public static final int FAMILY_PARAMETRO = 50;
  public static final int MAYOR_IGUAL = 61;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOR_QUE",
  "MAYOR_QUE",
  "DIAGONAL",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "IGUAL",
  "C_GCIC",
  "C_HEAD",
  "C_TITLE",
  "C_LINK",
  "LINK_PARAMETRO",
  "C_BODY",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "C_H1",
  "C_P",
  "C_SCRIPTING",
  "ID",
  "NAME",
  "BACKGROUND",
  "COLOR",
  "COLOR_PARAMETRO",
  "FONT_SIZE",
  "FONT_FAMILY",
  "TEXT_ALIGN",
  "TYPE",
  "COLS",
  "ROWS",
  "ENTERO",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "HREF",
  "SIZE_PARAMETRO_IMAGEN",
  "SIZE_PARAMETRO",
  "FAMILY_PARAMETRO",
  "ALING_PARAMETRO",
  "TYPE_PARAMETRO",
  "NOMBRE_FUNCION_PARAMETRO",
  "TEXTO_ETIQUETA",
  "ID_PARAMETRO",
  "ID_PARAMETRO_ELEMENT",
  "ID_PARAMETRO_INSERT",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "TIPOS_DATOS",
  "ID_VARIABLE",
  "GLOBAL",
  "NOMBRE_FUNCION",
  "ON_LOAD",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "REDIRECT",
  "INSERT",
  "GET_ELEMENT_BY_ID",
  "INIT",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "INTEGER_NEGATIVO",
  "INTEGER_POSITIVO",
  "STRING_PARAMETRO",
  "DECIMAL_POSITIVO",
  "DECIMAL_NEGATIVO",
  "BOOLEAN",
  "CARACTER",
  "MULTIPLICACION",
  "SUMA",
  "RESTA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "OPERADOR_Y",
  "OPERADOR_O",
  "NOT"
  };
}

