
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package reportes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 3;
  public static final int FALLAS = 6;
  public static final int EOF = 0;
  public static final int NUMERO = 9;
  public static final int LLAVE_CERRADA = 5;
  public static final int error = 1;
  public static final int USOS = 8;
  public static final int DOS_PUNTOS = 2;
  public static final int ACIERTOS = 7;
  public static final int LLAVE_ABIERTA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOS_PUNTOS",
  "COMA",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "FALLAS",
  "ACIERTOS",
  "USOS",
  "NUMERO"
  };
}

